### ISSUE TITLE
whose view is not in the window hierarchy!

### ISSUE THREAD

**Issue by stealdre** [IvanVorobei/RequestPermission#1]
I get this error: "Sparrow.SPRequestPermissionDialogInteractiveViewController: ... whose view is not in the window hierarchy!".

I setup the RequestPermission like this:

```
var permissionAssistant = SPRequestPermissionAssistant.modules.dialog.interactive.create(with: [.Location, .PhotoLibrary, .Notification])

override func viewDidAppear(animated: Bool) {
        permissionAssistant.present(on: self)
}
```

Thanks.

**Comment by stealdre** [comment]
It only works when I use it with a button... I want it to appear when the view appears.

**Comment by davnag** [comment]
Try it in viewDidAppear

**Comment by IvanVorobei** [comment]
@stealdre, thanks for your feedback!
I try repeat this mistake, but could not. @davnag is rights, it is necessary to call a function in viewDidAppear. But your do it. 

Tell us more about the issue. The controller present with a mistake or just a mistake? How does this affect application performance? Any information that would help me to reproduce this problem

**Comment by stealdre** [comment]
I don't know... I only did what I said: 
- import Sparrow
- init permission assistant var like above
-`permissionAssistant.present(on: self)` in the `viewDidAppear()`

This issue also occur in `viewDidAppear()` but this works with a button.
I have a simple `viewController`. I tried with an other `viewController`, same issue.
This is not affecting the application performances.
"The controller present with a mistake or just a mistake?" What do you mean?

**Comment by IvanVorobei** [comment]
@stealdre you call **super**? 

```
override func viewDidAppear(animated: Bool) {
        **super.viewDidAppear(animated: Bool)**
        permissionAssistant.present(on: self)
}
```

**Comment by stealdre** [comment]
what's the super for?

**Comment by stealdre** [comment]
I tried to call it but still not working...

**Comment by IvanVorobei** [comment]
@stealdre please, show full class your ViewController

**Comment by stealdre** [comment]
http://pastebin.com/UEGK4srL

**Comment by IvanVorobei** [comment]
@davnag I tried to show this mistake, but did not see it. Your code works well for me

**Comment by stealdre** [comment]
Arf...

**Comment by stealdre** [comment]
I also have all these errors: http://pastebin.com/ZvP5ep48

**Comment by IvanVorobei** [comment]
@stealdre It is normal. In sparrow use BezierPath for small size image

**Comment by IvanVorobei** [comment]
@stealdre The error you see using the simulator or device? The controller is presented or not?

**Comment by stealdre** [comment]
"In sparrow use BezierPath for small size image" Can you explain this? 
This errors come with simulator and with my device...

**Comment by IvanVorobei** [comment]
@davnag in sparrow used BezierPath for drawRect. It used without context, and show warnings. It is not mistake. All right

**Comment by stealdre** [comment]
OK so that's not the cause of my issue?

**Comment by stealdre** [comment]
I found something: I need to user a timer before to perform my function a bit later like this: 

```
    override func viewDidAppear(_ animated: Bool) {
        super.viewDidAppear(true)
        _ = Timer.scheduledTimer(timeInterval: 0.4, target: self, selector: #selector(self.checkPermissionsState), userInfo: nil, repeats: false);
    }
```

This is working. Maybe the loading of the view is too long and my function is performed before the view did appear...

**Comment by IvanVorobei** [comment]
@davnag if you use delay - all right? I do not understand what is the problem. I have everything working without delay...

**Comment by stealdre** [comment]
I don't know ahah this is strange! :p
