### ISSUE TITLE
Broken UI on landscape

### ISSUE THREAD

**Issue by julien-sarazin** [IvanVorobei/RequestPermission#14]
![img_0444](https://cloud.githubusercontent.com/assets/1331781/25039819/028bfc74-2106-11e7-85bb-4f90e0c3b28a.jpg)

Default DataSource is broken when putting the device on landscape (iPhone 7)

**Comment by IvanVorobei** [comment]
For me all correctly. Maybe you use BG without mask 
![simulator screen shot apr 14 2017 16 52 15](https://cloud.githubusercontent.com/assets/10995774/25045044/bf80dec2-2132-11e7-8160-52879e7c4600.png)
