### ISSUE TITLE
Location in background permission

### ISSUE THREAD

**Issue by rostopira** [IvanVorobei/RequestPermission#15]
My app needs geofencing tracking, so it requires another one permission

**Comment by IvanVorobei** [comment]
Describe the resolution that you need, I'll try to add

**Comment by IvanVorobei** [comment]
Describe the permission that you need, I'll try to add

**Comment by rostopira** [comment]
I mean permission which appears after `requestAlwaysAuthorization()`
```
let locMan = CLLocationManager()
locMan.requestAlwaysAuthorization()
```

**Comment by IvanVorobei** [comment]
@rostopira if I added it in current location, it is ok? Or create other location permission?

**Comment by rostopira** [comment]
@IvanVorobei for me it's ok, but I don't think other apps need that =)

**Comment by IvanVorobei** [comment]
@rostopira please, describe difference between my location permission and it's?

**Comment by rostopira** [comment]
@IvanVorobei just checked, it requests what I need:
![screen shot 2017-04-17 at 14 56 37](https://cloud.githubusercontent.com/assets/16724952/25088336/4be28a44-237e-11e7-8175-06db23fb898b.png)

But I'm not sure, that every app needs it

**Comment by IvanVorobei** [comment]
@rostopira I added it.
Use 
`SPRequestPermissionType.LocationWithBackground` if need location with background mode

 Thanks for your help!
