### ISSUE TITLE
cocoapod support?

### ISSUE THREAD

**Issue by jlaws** [IvanVorobei/RequestPermission#2]

**Comment by IvanVorobei** [comment]
See the "Integration" in the Readme

**Comment by rostopira** [comment]
Installation via CocoaPod not working for me. Blames on line "import Sparrow"

**Comment by IvanVorobei** [comment]
@rostopira I created an empty project and tried to integrate it - everything works correctly

**Comment by rostopira** [comment]
On second try worked 0_o Anyway, thanks
