### ISSUE TITLE
Allow Escalating Location Permissions

### ISSUE THREAD

**Issue by mgt-la** [IvanVorobei/RequestPermission#20]
If a user upon first launch authorizes .locationWhenInUse, and then later, when taking a certain action, needs to authorize .locationAlways, it shows as denied and that they need to change the settings from iPhone App settings. In fact, it is possible to upgrade from here, in-app, without going to the iPhone App Settings. (:

**Comment by IvanVorobei** [comment]
@mgt-la It's not posssible. If later you need use . locationAlways, you should request it. Apple allows to request location permissions only once

**Comment by mgt-la** [comment]
It works on PermissionScope which is another Pod like yours and apple has approved it. I just preferred this UX out of the box 🙂

**Comment by mgt-la** [comment]
Just tested, this works, if you press btn1, accept, then press btn2 and accept.

        
    import UIKit
    import Sparrow
    import CoreLocation
    class ViewController: UIViewController, CLLocationManagerDelegate {

      let manager = CLLocationManager()

      @IBAction func btn1(_ sender: Any) {                
          //SPRequestPermission.dialog.interactive.present(on: self, with: [.locationWhenInUse])
          manager.requestWhenInUseAuthorization()
      }

      @IBAction func btn2(_ sender: Any) {
          
          //SPRequestPermission.dialog.interactive.present(on: self, with: [.notification,.locationAlways])
          manager.requestAlwaysAuthorization()
      }
    }

**Comment by IvanVorobei** [comment]
@mgt-la I find how do it, in one hour I will update pod

**Comment by mgt-la** [comment]
🙏🤞😬 😃🏆

**Comment by IvanVorobei** [comment]
@mgt-la please, say me, need change permission from .always to .whenInUse?

**Comment by IvanVorobei** [comment]
@mgt-la I am updated pod, you can use it now. Thanks for your help!

**Comment by mgt-la** [comment]
@IvanVorobei sorry for the late reply- no, will never need to de-escalate back down to .whenInUse once .always is allowed.

Thank you!! You're awesome! This is a great pod and the other parts of Sparrow are a nice addition!
