### ISSUE TITLE
didRegisterForRemoteNotificationsWithDeviceToken

### ISSUE THREAD

**Issue by croossin** [IvanVorobei/RequestPermission#22]
When accepting the enable notification .. `didRegisterForRemoteNotificationsWithDeviceToken` is not being called... I would expect that to be the case? How else would I go about getting the device token after they accepted enabling notifications?

**Comment by IvanVorobei** [comment]
@croosin 
It must work. You can create empty project and try it again? Or send me your project, I am look at

**Comment by croossin** [comment]
I'm certain... must I do anything else special besides implementing that protocol function and including .notifications?

**Comment by IvanVorobei** [comment]
@croossin after native notification request you should get the token

Nothing do additional

**Comment by croossin** [comment]
So I just have to add .notifications to the array and then once they accept that should get fired, correct?

**Comment by IvanVorobei** [comment]
@croossin 

yes, when they accept notification request you get token

**Comment by croossin** [comment]
I just tried downloading your example project and it still does not call that? Are you sure there is nothing else needed to do.

**Comment by vmacavero** [comment]
chase, i'm on mobile so
i am not sure. Did you enable
push on xcode? and did you set permission privacy setting
in plist
file?
Victor

Il giorno 04 mag 2017, alle ore 16:40, Chase <notifications@github.com> ha scritto:

I just tried downloading your example project and it still does not call that? Are you sure there is nothing else needed to do.

**Comment by croossin** [comment]
Yes I have done all of that.  The example project doesn't even fire the call...

**Comment by vmacavero** [comment]
did you try on a real phone ?

Victor

2017-05-04 17:46 GMT+02:00 Chase <notifications@github.com>:

**Comment by croossin** [comment]
Yes tested on a real device...

**Comment by vmacavero** [comment]
give a look to this :
http://stackoverflow.com/questions/39403752/didregisterforremotenotificationswithdevicetoken-is-not-called-in-xcode-8

2017-05-04 19:40 GMT+02:00 Chase <notifications@github.com>:

**Comment by croossin** [comment]
Does the demo work while on Xcode 8... I will take a look at the SO
article.

**Comment by PavelKandziuba** [comment]
Guys did you enable push capabilities in Targets -> Capabilities? 
http://joxi.ru/bmoYMMpcVwE0Ay

I just tried and after enabling and reinstalling app - I got push token in App delegate call-back

**Comment by croossin** [comment]
Yes.  I'll try again :)

**Comment by croossin** [comment]
I have got it to work! Clean project, remove from device, reinstall... Sorry for the hassle!

**Comment by IvanVorobei** [comment]
Thank everybody for help!
