### ISSUE TITLE
Customization missing

### ISSUE THREAD

**Issue by batical** [IvanVorobei/RequestPermission#24]
Hello, 
I just start to use your lib and it is very nice, easy to use / configure .

I just have an issue with one customization. I am doing an app mainly in French, and there is one popup I did not manage to change / localize
![capture d ecran 2017-05-09 a 11 38 46](https://cloud.githubusercontent.com/assets/7248073/25844887/36c005e4-34ac-11e7-9a0a-26b0a6d57bf4.png)

I am asking the permission one at a time (when needed) so basically one by one. Is very a way to customize the text based on notification type (not very important and maybe to specific to my case)
edit :  I just plug my brain and ... I just have to create 2 datasources.... easy

thanks for you work

**Comment by IvanVorobei** [comment]
@batical Hello! You are right, I am forget create DataSource for this dialog

I can do it in few days. After update lib I will write here. 
Thank for your help!

**Comment by batical** [comment]
Thanks . I am not in a hurry :) will wait you found some times

**Comment by batical** [comment]
any news regarding this point ? thanks

**Comment by IvanVorobei** [comment]
@batical now I do some project and edit RequestPermission. Soon update with new permissions. Sorry for waiting

**Comment by IvanVorobei** [comment]
@batical I am update module and add DataSource items

Sorry for waiting and thank for you issue

**Comment by IvanVorobei** [comment]
@batical I am update module and add DataSource items

Sorry for waiting and thank for you issue

**Comment by batical** [comment]
Thanks a lot. No worries, it is great you change it. Plan to submit the first version of the app using your code in at least one week depending on last review
Thanks anyway
