### ISSUE TITLE
segmentation fault: 11 error 

### ISSUE THREAD

**Issue by Ahmedshubber** [IvanVorobei/RequestPermission#26]
@BasThomas @IvanVorobei @mgt-la @RobertGolosynsky @telunc I love this project very much. But there is an issue. Every time I download the project and build it I get a command failed due to signal: segmentation fault: 11 error. I tried everything from cleaning the project, to transferring the files directing into my project to using cocoa pods and nothing worked. Can you please help me resolve this so I can use this project.

**Comment by IvanVorobei** [comment]
Hi! Please, compress and send me your project

**Comment by Ahmedshubber** [comment]
[RequestPermission-master-2.zip](https://github.com/IvanVorobei/RequestPermission/files/1000969/RequestPermission-master-2.zip)

**Comment by Ahmedshubber** [comment]
@Ivanvorobei can you please give me an answer. I can't run my app right now without knowing the problem and it is your project.

**Comment by vmacavero** [comment]
@Ahmedshubber 
project works on my Mac. Last Xcode, iPhone6 iOS 10.1 Emulator

**Comment by Ahmedshubber** [comment]
@vmacavero I'm on iOS 10.2 and i keep getting the same error. Why

**Comment by Ahmedshubber** [comment]
@vmacavero do you mind skyping with me so i can show you that this is actually happening and I'm on the latest Xcode.

**Comment by IvanVorobei** [comment]
@Ahmedshubber, for me all works correctly. You have some troubles with Xcode on your machine
Try reinstall system or XCode

Sorry, I can't help you with this problem
