### ISSUE TITLE
black color

### ISSUE THREAD

**Issue by Ahmedshubber** [IvanVorobei/RequestPermission#28]
@IvanVorobei How can I change the black background color of the rhombus pattern. Which file is it so I can change it. Ive tried every single file and couldn't find it myself. I would appreciate it if you could help me find the property. for it. Thanks.

**Comment by IvanVorobei** [comment]
@Ahmedshubber see the DataSource method
<img width="741" alt="screen shot 2017-06-01 at 12 27 57" src="https://cloud.githubusercontent.com/assets/10995774/26673506/ccd3ecb4-46c5-11e7-8a09-cef673ac1b67.png">
