### ISSUE TITLE
Does not work with Xcode 9

### ISSUE THREAD

**Issue by CaptainYukinoshitaHachiman** [IvanVorobei/RequestPermission#29]
When I try to build my project,I get a strange error
If the destination is a simulator, the compiler will give this error:Command failed due to signal: Segmentation fault: 11
If the destination is a device in the real world,it will will give Command failed due to signal: Abort trap: 6

**Comment by IvanVorobei** [comment]
@CaptainYukinoshitaHachiman sorry, now lib don't support xCode 9
