### ISSUE TITLE
App rejected

### ISSUE THREAD

**Issue by davnag** [IvanVorobei/RequestPermission#3]
Got my app rejected due to:
"Push notifications must be optional and must obtain the user's consent to be used within the app."

<img width="768" alt="attachment-2238713732170665354screenshot_0308_095811" src="https://cloud.githubusercontent.com/assets/12034780/23740969/6240d7ec-04a6-11e7-835e-3121b89f3aa3.png">

In the picture the "Swipe to dismiss" isn´t visible, i don´t know why. So the user can´t get anywhere from here if the user don´t try to drag the popup.

To fix this i suggest that if you the user don´t allow permission the button should turn red with a cross and don´t show the alertview in the picture. That alert should only show when the user press that button again.
And when all permission is answered (allowed or denied) the popup should automatically close.

**Comment by IvanVorobei** [comment]
@davnag Thanks! I do it soon

**Comment by IvanVorobei** [comment]
I am update module and add custom logic for Notification

**Comment by davnag** [comment]
This is not just for Notification, i guess this apply for all permissions.

**Comment by IvanVorobei** [comment]
I think that if a camera is requested - it's exactly needed. So with all the rest. Notifications do not affect the application functionality, so they can be optional. In any case, you need to wipe out, if the user does not want to make a decision now. But, for example, if the application is working with a camera - the camera is necessary.

**Comment by davnag** [comment]
Yes i agree with what you are saying, but in my opinion your popup should only be a visual help to present the user with the alternative permissions. Not to force it. But it´s up to you. :)
