### ISSUE TITLE
Segmentation Fault 11

### ISSUE THREAD

**Issue by zpv** [IvanVorobei/RequestPermission#33]
SPRequestPermission.swift is producing a compilation error on given xcodeproj.
Fresh XCode installation on a NEW machine.

**Comment by MonicaBura22** [comment]
This error occurs also on the new Xcode 9 beta. When will a release be made that supports iOS 11? 
Error from log shows this: While silgen emitConstructor SIL function "@_T07Sparrow19SPRequestPermissionVACyc33_0261F672424E7F44BA85DF45C2D6AB49LlfC".
 for 'init()' at /Users/.../Pods/Sparrow/sparrow/modules/request-permissions/SPRequestPermission.swift:82:13

**Comment by omarojo** [comment]
I just commented the "private init() {}" in line 82... 
and that got rid of the error.. but Im not sure if that will affect any other logic of the library. @IvanVorobei  can you confirm ?

**Comment by IvanVorobei** [comment]
@omarojo with new Xcode this mistake not appear. I am update for Swift 4, please, try again! Thanks
