### ISSUE TITLE
Use of unresolved identifier 'SPRequestPermission'

### ISSUE THREAD

**Issue by kzorluoglu** [IvanVorobei/RequestPermission#37]
Hi Everyone,
i have this error message under Swift Compiler Error Panel , where is the problem?

**HomeViewController.swift:32:9: Use of unresolved identifier 'SPRequestPermission'**

```
    override func viewDidAppear(_ animated: Bool) {        
        SPRequestPermission.dialog.interactive.present(on: self, with: [.camera, .photoLibrary, .notification])
    }

**Comment by IvanVorobei** [comment]
You are import Sparrow (if install via pods)

**Comment by kzorluoglu** [comment]
it's works after Import Sparrow. Thanks.
