### ISSUE TITLE
CLLocationManager created in wrong thread

### ISSUE THREAD

**Issue by rostopira** [IvanVorobei/RequestPermission#38]
After user grants always on location usage I see the following warning in XCode console.
And looks like it's the cause of rare crashes in production.

`2017-08-10 14:48:20.317102 MY_APP[902:377336] A location manager (0x15fec6c0) was created on a dispatch queue executing on a thread other than the main thread.  It is the developer's responsibility to ensure that there is a run loop running on the thread on which the location manager object is allocated.  In particular, creating location managers in arbitrary dispatch queues (not attached to the main queue) is not supported and will result in callbacks not being received`

**Comment by IvanVorobei** [comment]
Please, call in in Main thread.
Its error show because you use not main thread
