### ISSUE TITLE
Xcode 9 / iOS 11

### ISSUE THREAD

**Issue by DannyJi** [IvanVorobei/RequestPermission#40]
Hi.  I was about to use this some app updates that are scheduled to be released in a few weeks.  I am reading about issues with Xcode 9/ iOS 11 in both closed issues and open ones with segmentation faults.

I have been using this stand-alone and trying subclassing, but I have not used cocoa pods to put it into my production code base.

Is there being work done to make this transition that we will soon be using?  I just do not want to incorporate this great framework if is not close to be ready for Xcode 9, etc.

**Comment by IvanVorobei** [comment]
Good day! Now I can add support iOS 11. Soon I am add

**Comment by rostopira** [comment]
I don't want to create new issue, so will just write it here.
iOS11 has major changes in location permissions.
Now if user manually set in settings to use location only when app opened `requestAlwaysAuthorization()` doesn't show any dialog

**Comment by IvanVorobei** [comment]
Thank for you work! 
I am update project to Swift 4
