### ISSUE TITLE
updatePermissionsStyle does not consider 

### ISSUE THREAD

**Issue by johnmci** [IvanVorobei/RequestPermission#41]
If you have say enable MicroPhone, and Enable Location (whenAppInUse) and you enable the microphone, but reply NO to the request to enable location, then jump to the Settings App and allow it, then jump back to the app 

Then the updatePermissionsStyle() function runs via the request earlier made via 
NotificationCenter.default.addObserver(self, selector: #selector(self.updatePermissionsStyle), name: NSNotification.Name.UIApplicationDidBecomeActive, object: nil)

But this does not trigger the  SPRequestPermissionDialogInteractivePresenter>>actionForControl logic that would run the if allPermissionAllowed {} logic to autoclose the dialog view controller. Rather it just invokes  control.setSelectedState(animated: false) for each permission that is true. 

The end result is the dialog does not autoclose, nor does the caller's delegate methods viaSPRequestPermissionEventsDelegate get invoked to do any special processing. 

notes: perhaps on the app going inactive you'll have to remember state of permissions so you can properly fire delegate methods based on state change found in activation.

**Comment by IvanVorobei** [comment]
Thanks for information! 
Soon I am fix it
