### ISSUE TITLE
Disabling drag to dismiss animation

### ISSUE THREAD

**Issue by uddinr** [IvanVorobei/RequestPermission#47]
is there any way to disable the "wobbling" animation when closing the dialog in other words just closing straight down?

**Comment by IvanVorobei** [comment]
I did not quite understand.
The window closes either linearly, or by a gesture of brushing down

**Comment by uddinr** [comment]
see attached screenshots, rather than the dialog tilting i would like the dialog to remain straight when swiping down, what do you mean by linearly? it would be appreciated if it could be optional to simplify the animation rather than the physics of bouncing around


![simulator screen shot - iphone 8 - 2017-11-30 at 17 31 42](https://user-images.githubusercontent.com/18418023/33445309-6b633d40-d5f4-11e7-8994-84682a8aa6c2.png)
![simulator screen shot - iphone 8 - 2017-11-30 at 17 31 34](https://user-images.githubusercontent.com/18418023/33445310-6b80c50e-d5f4-11e7-8d3d-96108f623d46.png)

**Comment by IvanVorobei** [comment]
I understood what you mean. In the future update I will add the ability to customize this

**Comment by IvanVorobei** [comment]
Good day! Soon the release of a new version, you should study it when it comes out.

**Comment by ThoseGuysInTown** [comment]
was this ever added? Can't seem to find anything in the example project

**Comment by IvanVorobei** [comment]
@ThoseGuysInTown yes, please, see `Readme`
