### ISSUE TITLE
Location Permission is not usable

### ISSUE THREAD

**Issue by mlch911** [IvanVorobei/RequestPermission#48]
Press the location permission button and nothing happen, while other permissions like camera ,photo are usable.

**Comment by xpdavidx** [comment]
I also had this issue,  but it happens only after pressing option "while in use", then it stops working. For other permissions it at list  open pop-up, which offers to open the settings, but in specified scenario it's not working.

**Comment by mlch911** [comment]
I found out what was wrong with the permission. 
You must add all the privacy of location in the info.plist to make the location permission working.
And after I add those things, the request button is working nicely.
