### ISSUE TITLE
localized the text ?

### ISSUE THREAD

**Issue by ewan34500** [IvanVorobei/RequestPermission#5]
Currently we haven't possibility to localized text permission, do you think you can integrate this functionnality soon ?

**Comment by IvanVorobei** [comment]
You should implement DataSource with Localizable strings

**Comment by CaptainYukinoshitaHachiman** [comment]
Have you worked it out? Would you please show how didi you localize it?

**Comment by IvanVorobei** [comment]
Create new DataSource, and when create an object RequestPermission - add it as func parameters.
