### ISSUE TITLE
Hide header view

### ISSUE THREAD

**Issue by Xedart** [IvanVorobei/RequestPermission#52]
I don't want 'headerView' to appear in dialog. I don't really get its purpose. 
![request-permission_presenters](https://user-images.githubusercontent.com/13368688/39674633-60980ef2-5157-11e8-8424-b70afa24f31a.png)

See highlighted part - that's the only thing I want to leave. 
How can I achieve that?
Thank you for your work

**Comment by Xedart** [comment]
Eventually I managed to accomplish this by making a lot of changes here and there in your sources. It took some efforts, but I guess if there should be a simple way of doing that?

**Comment by IvanVorobei** [comment]
Good day! Soon the release of a new version, you should study it when it comes out.
