### ISSUE TITLE
Distingish button for locationAlways and locationWhenInUse

### ISSUE THREAD

**Issue by Ghenty** [IvanVorobei/RequestPermission#54]
Hi,
is there a possibility to change the text for button "Enable Location" in case of locationAlways to "Enable Location Always"?
Otherwise users will be confused, because they do not know which of the Location Options are required to grant.

Thanks,
Ghent

**Comment by IvanVorobei** [comment]
Good day! Soon the release of a new version, you should study it when it comes out.
