### ISSUE TITLE
Crashes on iOS 8.4,  8.3 devices

### ISSUE THREAD

**Issue by mukyasa** [IvanVorobei/RequestPermission#6]
The project is crashing in iOS 8 devices, Can u help me out in this

**Comment by IvanVorobei** [comment]
@mukyasa, pleas, describe what happen and add screenshot or video

**Comment by mukyasa** [comment]
public init(withRadius radius: CGFloat) {
        let customBlurClass: AnyObject.Type = NSClassFromString("_UICustomBlurEffect")

in SPBlurView class

crashing on this line

**Comment by IvanVorobei** [comment]
@mukyasa you closed this issue, not I am. 
Now I check this problem and fixing it

**Comment by mukyasa** [comment]
sorry, actually i didnt closed this may be this happened through mail

**Comment by IvanVorobei** [comment]
@mukyasa I fixed it, you can update project

**Comment by mukyasa** [comment]
thnks @IvanVorobei
