### ISSUE TITLE
Pod install failure

### ISSUE THREAD

**Issue by Henry-** [IvanVorobei/RequestPermission#62]
I added pod 'SPRequestPermission'

[!] Unable to find a specification for 'SPRequestPermission'.

I tried 'pod repo update' & downloading from the `https://github.com/IvanVorobei/RequestPermission.git` as well and it did not work?

**Comment by IvanVorobei** [comment]
Sorry, real mistake in readme
I am fix it now

Please, use `pod 'SPPermission'`

**Comment by Henry-** [comment]
Thank you very much!

**Comment by Yurssoft** [comment]
I have same issue, I'm using `pod 'SPPermission'`. Porobably it needs some additional setup?
Thanks in advance.
<img width="485" alt="screen shot 2018-12-06 at 15 20 29" src="https://user-images.githubusercontent.com/7051552/49586671-7d5e9400-f96a-11e8-998e-bb86a6f0312b.png">

**Comment by IvanVorobei** [comment]
@Henry- please, use 'pod update'. Now ok?

**Comment by IvanVorobei** [comment]
@Yurssoft sorry, mistake)
